### ISSUE TITLE
How install from yarn or npm

### ISSUE THREAD

**Issue by rustam87** [HaoyCn/sprite-plugin-webpack#1]

**Comment by HaoyCn** [comment]
You can install it from npm: https://www.npmjs.com/package/sprite-plugin-webpack

```
npm install sprite-plugin-webpack --save
```

**Comment by rustam87** [comment]
Your plugin can work corect with ExtractTextPlugin?

**Comment by HaoyCn** [comment]
Sure. It doesn't have any connections with ExtractTextPlugin.
The only thing this plugin does is to generate image and scss(by default) files.

**Comment by rustam87** [comment]
i am not found option that real path to img in sprite.scss

**Comment by rustam87** [comment]
i am finding plugin 2 days. I stop for that - https://www.npmjs.com/package/webpack-spritesmith
But my webpack restart 20 time with this plugin.
Author say me that because i use with ExtractTextPlugin, but that plugin does not coonection with Extract too

**Comment by HaoyCn** [comment]
You can use `imagePath` option to set a string as the url in the scss file.
By default the url path is calculated with `option.dest.image` and `option.dest.css`.

If you use the default scss template, you can try `@include sprite-item()` and `@include sprite-position()`. What's more, `sprite-info()` and `sprite-prop` can help you to get specified property.

**Comment by rustam87** [comment]
this is analogy spriteSmith for gulp?

**Comment by HaoyCn** [comment]
Yeah. The core dependency is exactly `spritesmith`.

**Comment by rustam87** [comment]
Can you to perfomace example how to use sprite my files.
SpriteSmith for gulp say that include sprite.scss and i use 
.icon-home {
     @include sprite($home)
}

**Comment by HaoyCn** [comment]
Input:

```scss
.head-home {
    @include sprite-item('home');
    
    &:hover {
        @include sprite-position('home_hover');
    }
}

.head-back {
    @include sprite-item('back');
}
```

Output:
```css
.head-home,
.head-back {
  background-image: url(path/to/sprite.png);
}
.head-home {
  width: 12px;
  height: 12px;
  background-position: -56px -48px;
}
.head-home:hover {
  background-position: -0px -0px;
}
.head-back {
  width: 18px;
  height: 20px;
  background-position: -18px -20px;
}
```

**Comment by rustam87** [comment]
When i use retina 


Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-verbose" "/app/mobile/web/img/sprite-icons/check-off.png" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (/app/node_modules/gm/lib/command.js:232:12)
    at emitOne (events.js:115:13)
    at ChildProcess.emit (events.js:210:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by HaoyCn** [comment]
You have to install the software `GraphicsMagick`: http://www.graphicsmagick.org/download.html

**Comment by rustam87** [comment]
Not Working. 
Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-verbose" "/app/mobile/web/img/sprite-icons/check-off.png" this most likely means the gm/convert binaries can't be found

Plugin work correc, but not working retina

**Comment by rustam87** [comment]
1.I must install the software GraphicsMagick
2. i must  npm install gm -g

OR
 i must  npm install gm -g or must install the software GraphicsMagick

**Comment by HaoyCn** [comment]
You should do both.

----------

When `useRetina: true`, the results from `@sprite-item` and `@sprite-position` are 2x. You can write your scss numbers in 2x (the original sizes you get for your PSD files), and use `postcss-px-editor` to divide the numbers.

Or you can define your own `@mixin`s with `sprite-prop`. For example:

```scss
@mixin sprite-item-normal($sprite) {
    $x: unquote(sprite-prop($sprite, 'x', false) + 'px');
    $y: unquote(sprite-prop($sprite, 'y', false) + 'px');
    $total_width: unquote(sprite-prop($sprite, 'total_width', false) + 'px');
    $total_height: unquote(sprite-prop($sprite, 'total_height', 'false') + 'px');
    $url: unquote(sprite-prop($sprite, 'url', false));
    width: unquote(sprite-prop($sprite, 'width', false) + 'px');
    height: unquote(sprite-prop($sprite, 'height', false) + 'px');
    background: url($url) $x $y no-repeat;
    background-size: $total_width $total_height;
}
```

**Comment by HaoyCn** [comment]
Can you post your webpack config please?

**Comment by HaoyCn** [comment]
Do not name your sprite icons with `-`. Use `_` instead. The plugin may treat `-` as a group identifier.

And use `imagePath` option to define the sprite url in the scss file.

**Comment by rustam87** [comment]
ok, please say when i use retina, my output is 2 sprite(retina and normal) or 1 sprite(retina+normal).
Now i have sprite with icon + icon dublicate. But icon dublicate is not retina
Example https://i.imgur.com/Ez09Jpy.jpg

**Comment by HaoyCn** [comment]
You don't need to prepare normal icons. And name your icons like `check_off@2x.png`( don't use `-` ).

**Comment by rustam87** [comment]
that ok, but i write 
@include sprite-item('checkon');
I output icon for size for retina
    width: 40px;
    height: 40px;

But i want normal size
{
    width: 20px;
    height: 20px;
}

**Comment by HaoyCn** [comment]
As for the sizes, see my comment: https://github.com/HaoyCn/sprite-plugin-webpack/issues/1#issuecomment-332533761

**Comment by rustam87** [comment]
You can add this to plugin?

**Comment by HaoyCn** [comment]
Sorry I don't think that it's necessary to add this because `sprite-prop()` can help us to do anything.

I myself love to write scss units as what they are in PSDs, and use `postcss-px-editor` to automatically divide them. If you use `postcss-loader` I'd love to show you how to define it. For example:

```javascript
var pxeditor = require('postcss-px-editor');
var plugins = [
  // `warn=true`:  log values that are odd
  // `min=3`:   and don't divide numbers of which absolute values are less than 3
  pxeditor('divide-by-two?warn=true&min=3')
];
module.exports = {
  module: {
    rules: [
       {
          test: /\.scss$/,
          loaders: [
            'css-loader',
            { loader: 'postcss-loader', options: { plugins: plugins } },
            'sass-loader'
          ]
       }
    ]
  }
}

**Comment by rustam87** [comment]
What doing pxeditor? I dont find describe them

**Comment by HaoyCn** [comment]
Hum... it's a plugin I wrote. `postcss-px-editor` can help us to edit pxiel values in CSS. It accepts `Array`, `String` (built-in functions) and `Function`. For example:

```javascript
pxeditor([
  // built-in function: divide px values by 2
  'divide-by-two?warn=true&min=3',
  // log values
  function log(val) {
    console.log(val);
    return val;
  }
])
```

`PX` unit won't be handled by `postcss-px-editor`. So you can skip some values by writing them like  `13PX`.

**Comment by rustam87** [comment]
I deside to use your mixin, 
You plugin work good, but browser download retina spite for screen with pixel-ratio less 2

**Comment by rustam87** [comment]
and 2 question
1. Watch working only remove img
2.Can i add hash to sprite and it will be correct worki when webpack build?  Old sprite rewrite or new sprite add near old sprite?

**Comment by HaoyCn** [comment]
The template results in like:

```css
.some-icon {
    background-image: url('path/to/retina/sprite.png');
    background-image: image-set(url('path/to/normal/sprite.png') 1x, url('path/to/retina/sprite.png') 2x);
}
```

The key is `image-set`. Usually `autoprefixer` can transform it into `-webkit-image-set`. It seems that you don't use `autoprefixer`.

I will update the template file.
